### ISSUE TITLE
File missing: rules/lib/Util.lua

### ISSUE THREAD

**Issue by ashlaban** [nijoakim/chakes#2]
The file `Chess.lua` tries to load this file but fails to find it. Seems to be missing from repo.

The path seems somewhat strange to me, should there really be a `lib` folder under `rules`?

**Comment by nijoakim** [comment]
Committed the missing folder. It was ignored due to .gitignores lib/ line, which also apparently ignores non-root folders.

While the path is not a mistake, it may be a little weird to have it there and I'm up for changing it if we get better ides. The reasoning is all the lua files are placed in the rules folder and since I figured, one might want to use shared code between games, I'll make a library folder in the lua root.

To make it a little less weird, we could rename rules to lua? If you check out Utils.lua, you'll see that it includes just to functions, one to copy a table and one signum function. Some later research revealed that those functions are available in a semi-offical (i.e. not official, but it seems to be the thing people uses) library called penlight which provides many common functions, so it might be better to provide that by default and scrap the lib idea. What do you think?

**Comment by ashlaban** [comment]
Yes, changing the name of the `rules` folder to `lua` would resolve all confusing, I think. I then propse that the scala code is put in a similar structure rooted at `scala`. Thoughts?

**Comment by nijoakim** [comment]
Sounds great!, and implemented in my latest commit!
